name: argodataprocessing
dependencies:
    - colour
    - descartes
    - imageio
    - matplotlib
    - motmetrics==1.1.3
    - numpy
    - opencv-python>=4.1.0.25
    - pandas>=0.23.1
    - pillow
    - imageio
    - scipy>=1.4.0
    - shapely
    - sklearn
    - typing_extensions
    - h5py
    - lap
    - joblib
    - pip
    - pip:
        - git+https://github.com/daavoo/pyntcloud#egg=pyntcloud-0.1.0